apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: us-central1-docker.pkg.dev/high-apricot-364413/web-infra-template/backend
  newTag: latest

resources:
- ingress.yaml
- backend.yaml